name = "lithhash/oblivis"
version = "0.1.0"
description = "A general roblox game framework"
authors = ["LithHash"]
repository = "https://github.com/LithHash/Oblivis"
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dependencies]
alloyecs = { name = "lithhash/alloyecs", version = "^0.1.23" }
packet = { name = "lithhash/packet", version = "^0.1.21" }
coppermind = { name = "lithhash/coppermind", version = "^0.1.11" }
